name = "skillshare-cc"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "USERS"
id = "7060fa1565d14685b342b01b3a9e8b79"

[[kv_namespaces]]
binding = "INBOX"
id = "5fbf79fd7ac54323a515a46d123e5dc0"
